import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Grid } from '../../components/atoms/grid';
import { Surface } from '../../components/atoms/surface';
import { Text } from '../../components/atoms/text';
import { withPageSessionMiddleware } from '../../middlewares/PageSessionMiddleware';

const Home: NextPage = () => {
  return (
    <Grid.Wrapper>
      <Head>
        <title>Invoices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Item gridColumn="1/13" gridRow="1">
        <Text size="xxLarge">Invoices</Text>
      </Grid.Item>
    </Grid.Wrapper>
  );
};

export default Home;

const serverSideProps: GetServerSideProps = async ({ req }) => {
  const { user } = req.session;

  return {
    props: {},
  };
};
export const getServerSideProps = withPageSessionMiddleware(serverSideProps);
